// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partnerNotifyOfPeeredModified.proto

package waldo_protobuffs;

public final class PartnerNotifyOfPeeredModifiedProto {
  private PartnerNotifyOfPeeredModifiedProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PartnerNotifyOfPeeredModifiedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .UUID event_uuid = 1;
    boolean hasEventUuid();
    waldo_protobuffs.UtilProto.UUID getEventUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder();
    
    // required .Priority priority = 2;
    boolean hasPriority();
    waldo_protobuffs.UtilProto.Priority getPriority();
    waldo_protobuffs.UtilProto.PriorityOrBuilder getPriorityOrBuilder();
    
    // required .UUID reply_with_uuid = 3;
    boolean hasReplyWithUuid();
    waldo_protobuffs.UtilProto.UUID getReplyWithUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getReplyWithUuidOrBuilder();
    
    // required .VarStoreDeltas glob_deltas = 4;
    boolean hasGlobDeltas();
    waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas getGlobDeltas();
    waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltasOrBuilder getGlobDeltasOrBuilder();
  }
  public static final class PartnerNotifyOfPeeredModified extends
      com.google.protobuf.GeneratedMessage
      implements PartnerNotifyOfPeeredModifiedOrBuilder {
    // Use PartnerNotifyOfPeeredModified.newBuilder() to construct.
    private PartnerNotifyOfPeeredModified(Builder builder) {
      super(builder);
    }
    private PartnerNotifyOfPeeredModified(boolean noInit) {}
    
    private static final PartnerNotifyOfPeeredModified defaultInstance;
    public static PartnerNotifyOfPeeredModified getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartnerNotifyOfPeeredModified getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.internal_static_PartnerNotifyOfPeeredModified_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.internal_static_PartnerNotifyOfPeeredModified_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .UUID event_uuid = 1;
    public static final int EVENT_UUID_FIELD_NUMBER = 1;
    private waldo_protobuffs.UtilProto.UUID eventUuid_;
    public boolean hasEventUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public waldo_protobuffs.UtilProto.UUID getEventUuid() {
      return eventUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
      return eventUuid_;
    }
    
    // required .Priority priority = 2;
    public static final int PRIORITY_FIELD_NUMBER = 2;
    private waldo_protobuffs.UtilProto.Priority priority_;
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public waldo_protobuffs.UtilProto.Priority getPriority() {
      return priority_;
    }
    public waldo_protobuffs.UtilProto.PriorityOrBuilder getPriorityOrBuilder() {
      return priority_;
    }
    
    // required .UUID reply_with_uuid = 3;
    public static final int REPLY_WITH_UUID_FIELD_NUMBER = 3;
    private waldo_protobuffs.UtilProto.UUID replyWithUuid_;
    public boolean hasReplyWithUuid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public waldo_protobuffs.UtilProto.UUID getReplyWithUuid() {
      return replyWithUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getReplyWithUuidOrBuilder() {
      return replyWithUuid_;
    }
    
    // required .VarStoreDeltas glob_deltas = 4;
    public static final int GLOB_DELTAS_FIELD_NUMBER = 4;
    private waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas globDeltas_;
    public boolean hasGlobDeltas() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas getGlobDeltas() {
      return globDeltas_;
    }
    public waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltasOrBuilder getGlobDeltasOrBuilder() {
      return globDeltas_;
    }
    
    private void initFields() {
      eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      priority_ = waldo_protobuffs.UtilProto.Priority.getDefaultInstance();
      replyWithUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      globDeltas_ = waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasEventUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReplyWithUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGlobDeltas()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEventUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPriority().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getReplyWithUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getGlobDeltas().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, eventUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, priority_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, replyWithUuid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, globDeltas_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, eventUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, priority_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, replyWithUuid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, globDeltas_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModifiedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.internal_static_PartnerNotifyOfPeeredModified_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.internal_static_PartnerNotifyOfPeeredModified_fieldAccessorTable;
      }
      
      // Construct using waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventUuidFieldBuilder();
          getPriorityFieldBuilder();
          getReplyWithUuidFieldBuilder();
          getGlobDeltasFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (eventUuidBuilder_ == null) {
          eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (priorityBuilder_ == null) {
          priority_ = waldo_protobuffs.UtilProto.Priority.getDefaultInstance();
        } else {
          priorityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (replyWithUuidBuilder_ == null) {
          replyWithUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          replyWithUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (globDeltasBuilder_ == null) {
          globDeltas_ = waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.getDefaultInstance();
        } else {
          globDeltasBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified.getDescriptor();
      }
      
      public waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified getDefaultInstanceForType() {
        return waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified.getDefaultInstance();
      }
      
      public waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified build() {
        waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified buildPartial() {
        waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified result = new waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (eventUuidBuilder_ == null) {
          result.eventUuid_ = eventUuid_;
        } else {
          result.eventUuid_ = eventUuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (priorityBuilder_ == null) {
          result.priority_ = priority_;
        } else {
          result.priority_ = priorityBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (replyWithUuidBuilder_ == null) {
          result.replyWithUuid_ = replyWithUuid_;
        } else {
          result.replyWithUuid_ = replyWithUuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (globDeltasBuilder_ == null) {
          result.globDeltas_ = globDeltas_;
        } else {
          result.globDeltas_ = globDeltasBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified) {
          return mergeFrom((waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified other) {
        if (other == waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified.getDefaultInstance()) return this;
        if (other.hasEventUuid()) {
          mergeEventUuid(other.getEventUuid());
        }
        if (other.hasPriority()) {
          mergePriority(other.getPriority());
        }
        if (other.hasReplyWithUuid()) {
          mergeReplyWithUuid(other.getReplyWithUuid());
        }
        if (other.hasGlobDeltas()) {
          mergeGlobDeltas(other.getGlobDeltas());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasEventUuid()) {
          
          return false;
        }
        if (!hasPriority()) {
          
          return false;
        }
        if (!hasReplyWithUuid()) {
          
          return false;
        }
        if (!hasGlobDeltas()) {
          
          return false;
        }
        if (!getEventUuid().isInitialized()) {
          
          return false;
        }
        if (!getPriority().isInitialized()) {
          
          return false;
        }
        if (!getReplyWithUuid().isInitialized()) {
          
          return false;
        }
        if (!getGlobDeltas().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasEventUuid()) {
                subBuilder.mergeFrom(getEventUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEventUuid(subBuilder.buildPartial());
              break;
            }
            case 18: {
              waldo_protobuffs.UtilProto.Priority.Builder subBuilder = waldo_protobuffs.UtilProto.Priority.newBuilder();
              if (hasPriority()) {
                subBuilder.mergeFrom(getPriority());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPriority(subBuilder.buildPartial());
              break;
            }
            case 26: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasReplyWithUuid()) {
                subBuilder.mergeFrom(getReplyWithUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReplyWithUuid(subBuilder.buildPartial());
              break;
            }
            case 34: {
              waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.Builder subBuilder = waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.newBuilder();
              if (hasGlobDeltas()) {
                subBuilder.mergeFrom(getGlobDeltas());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGlobDeltas(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .UUID event_uuid = 1;
      private waldo_protobuffs.UtilProto.UUID eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> eventUuidBuilder_;
      public boolean hasEventUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public waldo_protobuffs.UtilProto.UUID getEventUuid() {
        if (eventUuidBuilder_ == null) {
          return eventUuid_;
        } else {
          return eventUuidBuilder_.getMessage();
        }
      }
      public Builder setEventUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventUuid_ = value;
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setEventUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = builderForValue.build();
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeEventUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              eventUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            eventUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(eventUuid_).mergeFrom(value).buildPartial();
          } else {
            eventUuid_ = value;
          }
          onChanged();
        } else {
          eventUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearEventUuid() {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getEventUuidBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEventUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
        if (eventUuidBuilder_ != null) {
          return eventUuidBuilder_.getMessageOrBuilder();
        } else {
          return eventUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getEventUuidFieldBuilder() {
        if (eventUuidBuilder_ == null) {
          eventUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  eventUuid_,
                  getParentForChildren(),
                  isClean());
          eventUuid_ = null;
        }
        return eventUuidBuilder_;
      }
      
      // required .Priority priority = 2;
      private waldo_protobuffs.UtilProto.Priority priority_ = waldo_protobuffs.UtilProto.Priority.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.Priority, waldo_protobuffs.UtilProto.Priority.Builder, waldo_protobuffs.UtilProto.PriorityOrBuilder> priorityBuilder_;
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public waldo_protobuffs.UtilProto.Priority getPriority() {
        if (priorityBuilder_ == null) {
          return priority_;
        } else {
          return priorityBuilder_.getMessage();
        }
      }
      public Builder setPriority(waldo_protobuffs.UtilProto.Priority value) {
        if (priorityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          priority_ = value;
          onChanged();
        } else {
          priorityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPriority(
          waldo_protobuffs.UtilProto.Priority.Builder builderForValue) {
        if (priorityBuilder_ == null) {
          priority_ = builderForValue.build();
          onChanged();
        } else {
          priorityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePriority(waldo_protobuffs.UtilProto.Priority value) {
        if (priorityBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              priority_ != waldo_protobuffs.UtilProto.Priority.getDefaultInstance()) {
            priority_ =
              waldo_protobuffs.UtilProto.Priority.newBuilder(priority_).mergeFrom(value).buildPartial();
          } else {
            priority_ = value;
          }
          onChanged();
        } else {
          priorityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPriority() {
        if (priorityBuilder_ == null) {
          priority_ = waldo_protobuffs.UtilProto.Priority.getDefaultInstance();
          onChanged();
        } else {
          priorityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public waldo_protobuffs.UtilProto.Priority.Builder getPriorityBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPriorityFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.PriorityOrBuilder getPriorityOrBuilder() {
        if (priorityBuilder_ != null) {
          return priorityBuilder_.getMessageOrBuilder();
        } else {
          return priority_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.Priority, waldo_protobuffs.UtilProto.Priority.Builder, waldo_protobuffs.UtilProto.PriorityOrBuilder> 
          getPriorityFieldBuilder() {
        if (priorityBuilder_ == null) {
          priorityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.Priority, waldo_protobuffs.UtilProto.Priority.Builder, waldo_protobuffs.UtilProto.PriorityOrBuilder>(
                  priority_,
                  getParentForChildren(),
                  isClean());
          priority_ = null;
        }
        return priorityBuilder_;
      }
      
      // required .UUID reply_with_uuid = 3;
      private waldo_protobuffs.UtilProto.UUID replyWithUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> replyWithUuidBuilder_;
      public boolean hasReplyWithUuid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public waldo_protobuffs.UtilProto.UUID getReplyWithUuid() {
        if (replyWithUuidBuilder_ == null) {
          return replyWithUuid_;
        } else {
          return replyWithUuidBuilder_.getMessage();
        }
      }
      public Builder setReplyWithUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (replyWithUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          replyWithUuid_ = value;
          onChanged();
        } else {
          replyWithUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setReplyWithUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (replyWithUuidBuilder_ == null) {
          replyWithUuid_ = builderForValue.build();
          onChanged();
        } else {
          replyWithUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeReplyWithUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (replyWithUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              replyWithUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            replyWithUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(replyWithUuid_).mergeFrom(value).buildPartial();
          } else {
            replyWithUuid_ = value;
          }
          onChanged();
        } else {
          replyWithUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearReplyWithUuid() {
        if (replyWithUuidBuilder_ == null) {
          replyWithUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          replyWithUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getReplyWithUuidBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getReplyWithUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getReplyWithUuidOrBuilder() {
        if (replyWithUuidBuilder_ != null) {
          return replyWithUuidBuilder_.getMessageOrBuilder();
        } else {
          return replyWithUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getReplyWithUuidFieldBuilder() {
        if (replyWithUuidBuilder_ == null) {
          replyWithUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  replyWithUuid_,
                  getParentForChildren(),
                  isClean());
          replyWithUuid_ = null;
        }
        return replyWithUuidBuilder_;
      }
      
      // required .VarStoreDeltas glob_deltas = 4;
      private waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas globDeltas_ = waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas, waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.Builder, waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltasOrBuilder> globDeltasBuilder_;
      public boolean hasGlobDeltas() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas getGlobDeltas() {
        if (globDeltasBuilder_ == null) {
          return globDeltas_;
        } else {
          return globDeltasBuilder_.getMessage();
        }
      }
      public Builder setGlobDeltas(waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas value) {
        if (globDeltasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          globDeltas_ = value;
          onChanged();
        } else {
          globDeltasBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setGlobDeltas(
          waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.Builder builderForValue) {
        if (globDeltasBuilder_ == null) {
          globDeltas_ = builderForValue.build();
          onChanged();
        } else {
          globDeltasBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeGlobDeltas(waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas value) {
        if (globDeltasBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              globDeltas_ != waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.getDefaultInstance()) {
            globDeltas_ =
              waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.newBuilder(globDeltas_).mergeFrom(value).buildPartial();
          } else {
            globDeltas_ = value;
          }
          onChanged();
        } else {
          globDeltasBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearGlobDeltas() {
        if (globDeltasBuilder_ == null) {
          globDeltas_ = waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.getDefaultInstance();
          onChanged();
        } else {
          globDeltasBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.Builder getGlobDeltasBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getGlobDeltasFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltasOrBuilder getGlobDeltasOrBuilder() {
        if (globDeltasBuilder_ != null) {
          return globDeltasBuilder_.getMessageOrBuilder();
        } else {
          return globDeltas_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas, waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.Builder, waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltasOrBuilder> 
          getGlobDeltasFieldBuilder() {
        if (globDeltasBuilder_ == null) {
          globDeltasBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas, waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltas.Builder, waldo_protobuffs.VarStoreDeltasProto.VarStoreDeltasOrBuilder>(
                  globDeltas_,
                  getParentForChildren(),
                  isClean());
          globDeltas_ = null;
        }
        return globDeltasBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:PartnerNotifyOfPeeredModified)
    }
    
    static {
      defaultInstance = new PartnerNotifyOfPeeredModified(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartnerNotifyOfPeeredModified)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartnerNotifyOfPeeredModified_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartnerNotifyOfPeeredModified_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#partnerNotifyOfPeeredModified.proto\032\nu" +
      "til.proto\032\024varStoreDeltas.proto\"\235\001\n\035Part" +
      "nerNotifyOfPeeredModified\022\031\n\nevent_uuid\030" +
      "\001 \002(\0132\005.UUID\022\033\n\010priority\030\002 \002(\0132\t.Priorit" +
      "y\022\036\n\017reply_with_uuid\030\003 \002(\0132\005.UUID\022$\n\013glo" +
      "b_deltas\030\004 \002(\0132\017.VarStoreDeltasB6\n\020waldo" +
      "_protobuffsB\"PartnerNotifyOfPeeredModifi" +
      "edProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PartnerNotifyOfPeeredModified_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PartnerNotifyOfPeeredModified_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartnerNotifyOfPeeredModified_descriptor,
              new java.lang.String[] { "EventUuid", "Priority", "ReplyWithUuid", "GlobDeltas", },
              waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified.class,
              waldo_protobuffs.PartnerNotifyOfPeeredModifiedProto.PartnerNotifyOfPeeredModified.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          waldo_protobuffs.UtilProto.getDescriptor(),
          waldo_protobuffs.VarStoreDeltasProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
