# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import util_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='heartbeat.proto',
  package='',
  serialized_pb='\n\x0fheartbeat.proto\x1a\nutil.proto\"\x18\n\tHeartbeat\x12\x0b\n\x03msg\x18\x01 \x02(\t')




_HEARTBEAT = descriptor.Descriptor(
  name='Heartbeat',
  full_name='Heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='msg', full_name='Heartbeat.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['Heartbeat'] = _HEARTBEAT

class Heartbeat(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEARTBEAT
  
  # @@protoc_insertion_point(class_scope:Heartbeat)

# @@protoc_insertion_point(module_scope)
