# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import util_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='partnerBackoutCommitRequest.proto',
  package='',
  serialized_pb='\n!partnerBackoutCommitRequest.proto\x1a\nutil.proto\"8\n\x1bPartnerBackoutCommitRequest\x12\x19\n\nevent_uuid\x18\x01 \x02(\x0b\x32\x05.UUID')




_PARTNERBACKOUTCOMMITREQUEST = descriptor.Descriptor(
  name='PartnerBackoutCommitRequest',
  full_name='PartnerBackoutCommitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='event_uuid', full_name='PartnerBackoutCommitRequest.event_uuid', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=105,
)

_PARTNERBACKOUTCOMMITREQUEST.fields_by_name['event_uuid'].message_type = util_pb2._UUID
DESCRIPTOR.message_types_by_name['PartnerBackoutCommitRequest'] = _PARTNERBACKOUTCOMMITREQUEST

class PartnerBackoutCommitRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTNERBACKOUTCOMMITREQUEST
  
  # @@protoc_insertion_point(class_scope:PartnerBackoutCommitRequest)

# @@protoc_insertion_point(module_scope)
