# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import util_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='partnerNotifyOfPeeredModifiedResponse.proto',
  package='',
  serialized_pb='\n+partnerNotifyOfPeeredModifiedResponse.proto\x1a\nutil.proto\"u\n%PartnerNotifyOfPeeredModifiedResponse\x12\x19\n\nevent_uuid\x18\x01 \x02(\x0b\x32\x05.UUID\x12\x13\n\x0binvalidated\x18\x02 \x02(\x08\x12\x1c\n\rreply_to_uuid\x18\x03 \x02(\x0b\x32\x05.UUID')




_PARTNERNOTIFYOFPEEREDMODIFIEDRESPONSE = descriptor.Descriptor(
  name='PartnerNotifyOfPeeredModifiedResponse',
  full_name='PartnerNotifyOfPeeredModifiedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='event_uuid', full_name='PartnerNotifyOfPeeredModifiedResponse.event_uuid', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='invalidated', full_name='PartnerNotifyOfPeeredModifiedResponse.invalidated', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reply_to_uuid', full_name='PartnerNotifyOfPeeredModifiedResponse.reply_to_uuid', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=176,
)

_PARTNERNOTIFYOFPEEREDMODIFIEDRESPONSE.fields_by_name['event_uuid'].message_type = util_pb2._UUID
_PARTNERNOTIFYOFPEEREDMODIFIEDRESPONSE.fields_by_name['reply_to_uuid'].message_type = util_pb2._UUID
DESCRIPTOR.message_types_by_name['PartnerNotifyOfPeeredModifiedResponse'] = _PARTNERNOTIFYOFPEEREDMODIFIEDRESPONSE

class PartnerNotifyOfPeeredModifiedResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTNERNOTIFYOFPEEREDMODIFIEDRESPONSE
  
  # @@protoc_insertion_point(class_scope:PartnerNotifyOfPeeredModifiedResponse)

# @@protoc_insertion_point(module_scope)
