# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import util_pb2
import varStoreDeltas_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='partnerRequestSequenceBlock.proto',
  package='',
  serialized_pb='\n!partnerRequestSequenceBlock.proto\x1a\nutil.proto\x1a\x14varStoreDeltas.proto\"\xa1\x02\n\x1bPartnerRequestSequenceBlock\x12\x19\n\nevent_uuid\x18\x01 \x02(\x0b\x32\x05.UUID\x12\x1b\n\x08priority\x18\x02 \x02(\x0b\x32\t.Priority\x12 \n\x18name_of_block_requesting\x18\x03 \x01(\t\x12\x1e\n\x0freply_with_uuid\x18\x04 \x02(\x0b\x32\x05.UUID\x12\x1c\n\rreply_to_uuid\x18\x05 \x01(\x0b\x32\x05.UUID\x12\x38\n\x1fsequence_local_var_store_deltas\x18\x06 \x02(\x0b\x32\x0f.VarStoreDeltas\x12\x30\n\x17peered_var_store_deltas\x18\x07 \x02(\x0b\x32\x0f.VarStoreDeltasB4\n\x10waldo_protobuffsB PartnerRequestSequenceBlockProto')




_PARTNERREQUESTSEQUENCEBLOCK = descriptor.Descriptor(
  name='PartnerRequestSequenceBlock',
  full_name='PartnerRequestSequenceBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='event_uuid', full_name='PartnerRequestSequenceBlock.event_uuid', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='priority', full_name='PartnerRequestSequenceBlock.priority', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name_of_block_requesting', full_name='PartnerRequestSequenceBlock.name_of_block_requesting', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reply_with_uuid', full_name='PartnerRequestSequenceBlock.reply_with_uuid', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reply_to_uuid', full_name='PartnerRequestSequenceBlock.reply_to_uuid', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sequence_local_var_store_deltas', full_name='PartnerRequestSequenceBlock.sequence_local_var_store_deltas', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='peered_var_store_deltas', full_name='PartnerRequestSequenceBlock.peered_var_store_deltas', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=361,
)

_PARTNERREQUESTSEQUENCEBLOCK.fields_by_name['event_uuid'].message_type = util_pb2._UUID
_PARTNERREQUESTSEQUENCEBLOCK.fields_by_name['priority'].message_type = util_pb2._PRIORITY
_PARTNERREQUESTSEQUENCEBLOCK.fields_by_name['reply_with_uuid'].message_type = util_pb2._UUID
_PARTNERREQUESTSEQUENCEBLOCK.fields_by_name['reply_to_uuid'].message_type = util_pb2._UUID
_PARTNERREQUESTSEQUENCEBLOCK.fields_by_name['sequence_local_var_store_deltas'].message_type = varStoreDeltas_pb2._VARSTOREDELTAS
_PARTNERREQUESTSEQUENCEBLOCK.fields_by_name['peered_var_store_deltas'].message_type = varStoreDeltas_pb2._VARSTOREDELTAS
DESCRIPTOR.message_types_by_name['PartnerRequestSequenceBlock'] = _PARTNERREQUESTSEQUENCEBLOCK

class PartnerRequestSequenceBlock(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTNERREQUESTSEQUENCEBLOCK
  
  # @@protoc_insertion_point(class_scope:PartnerRequestSequenceBlock)

# @@protoc_insertion_point(module_scope)
