# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='partnerStop.proto',
  package='',
  serialized_pb='\n\x11partnerStop.proto\"\x1c\n\x0bPartnerStop\x12\r\n\x05\x64ummy\x18\x01 \x02(\x08')




_PARTNERSTOP = descriptor.Descriptor(
  name='PartnerStop',
  full_name='PartnerStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dummy', full_name='PartnerStop.dummy', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['PartnerStop'] = _PARTNERSTOP

class PartnerStop(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTNERSTOP
  
  # @@protoc_insertion_point(class_scope:PartnerStop)

# @@protoc_insertion_point(module_scope)
