# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='partnerStop.proto',
  package='',
  serialized_pb='\n\x11partnerStop.proto\"\r\n\x0bPartnerStop')




_PARTNERSTOP = descriptor.Descriptor(
  name='PartnerStop',
  full_name='PartnerStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=34,
)

DESCRIPTOR.message_types_by_name['PartnerStop'] = _PARTNERSTOP

class PartnerStop(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTNERSTOP
  
  # @@protoc_insertion_point(class_scope:PartnerStop)

# @@protoc_insertion_point(module_scope)
