# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='util.proto',
  package='',
  serialized_pb='\n\nutil.proto\"\x14\n\x04UUID\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c')




_UUID = descriptor.Descriptor(
  name='UUID',
  full_name='UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='UUID.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=34,
)

DESCRIPTOR.message_types_by_name['UUID'] = _UUID

class UUID(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UUID
  
  # @@protoc_insertion_point(class_scope:UUID)

# @@protoc_insertion_point(module_scope)
