# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import util_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='partnerNotifyReady.proto',
  package='',
  serialized_pb='\n\x18partnerNotifyReady.proto\x1a\nutil.proto\"2\n\x12PartnerNotifyReady\x12\x1c\n\rendpoint_uuid\x18\x01 \x02(\x0b\x32\x05.UUID')




_PARTNERNOTIFYREADY = descriptor.Descriptor(
  name='PartnerNotifyReady',
  full_name='PartnerNotifyReady',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='endpoint_uuid', full_name='PartnerNotifyReady.endpoint_uuid', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=90,
)

_PARTNERNOTIFYREADY.fields_by_name['endpoint_uuid'].message_type = util_pb2._UUID
DESCRIPTOR.message_types_by_name['PartnerNotifyReady'] = _PARTNERNOTIFYREADY

class PartnerNotifyReady(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTNERNOTIFYREADY
  
  # @@protoc_insertion_point(class_scope:PartnerNotifyReady)

# @@protoc_insertion_point(module_scope)
