// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partnerRemovedSubscriber.proto

package waldo_protobuffs;

public final class PartnerRemovedSubscriberProto {
  private PartnerRemovedSubscriberProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PartnerRemovedSubscriberOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .UUID event_uuid = 1;
    boolean hasEventUuid();
    waldo_protobuffs.UtilProto.UUID getEventUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder();
    
    // required .UUID removed_subscriber_uuid = 2;
    boolean hasRemovedSubscriberUuid();
    waldo_protobuffs.UtilProto.UUID getRemovedSubscriberUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getRemovedSubscriberUuidOrBuilder();
    
    // required .UUID host_uuid = 3;
    boolean hasHostUuid();
    waldo_protobuffs.UtilProto.UUID getHostUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getHostUuidOrBuilder();
    
    // required .UUID resource_uuid = 4;
    boolean hasResourceUuid();
    waldo_protobuffs.UtilProto.UUID getResourceUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getResourceUuidOrBuilder();
  }
  public static final class PartnerRemovedSubscriber extends
      com.google.protobuf.GeneratedMessage
      implements PartnerRemovedSubscriberOrBuilder {
    // Use PartnerRemovedSubscriber.newBuilder() to construct.
    private PartnerRemovedSubscriber(Builder builder) {
      super(builder);
    }
    private PartnerRemovedSubscriber(boolean noInit) {}
    
    private static final PartnerRemovedSubscriber defaultInstance;
    public static PartnerRemovedSubscriber getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartnerRemovedSubscriber getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return waldo_protobuffs.PartnerRemovedSubscriberProto.internal_static_PartnerRemovedSubscriber_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return waldo_protobuffs.PartnerRemovedSubscriberProto.internal_static_PartnerRemovedSubscriber_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .UUID event_uuid = 1;
    public static final int EVENT_UUID_FIELD_NUMBER = 1;
    private waldo_protobuffs.UtilProto.UUID eventUuid_;
    public boolean hasEventUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public waldo_protobuffs.UtilProto.UUID getEventUuid() {
      return eventUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
      return eventUuid_;
    }
    
    // required .UUID removed_subscriber_uuid = 2;
    public static final int REMOVED_SUBSCRIBER_UUID_FIELD_NUMBER = 2;
    private waldo_protobuffs.UtilProto.UUID removedSubscriberUuid_;
    public boolean hasRemovedSubscriberUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public waldo_protobuffs.UtilProto.UUID getRemovedSubscriberUuid() {
      return removedSubscriberUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getRemovedSubscriberUuidOrBuilder() {
      return removedSubscriberUuid_;
    }
    
    // required .UUID host_uuid = 3;
    public static final int HOST_UUID_FIELD_NUMBER = 3;
    private waldo_protobuffs.UtilProto.UUID hostUuid_;
    public boolean hasHostUuid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public waldo_protobuffs.UtilProto.UUID getHostUuid() {
      return hostUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getHostUuidOrBuilder() {
      return hostUuid_;
    }
    
    // required .UUID resource_uuid = 4;
    public static final int RESOURCE_UUID_FIELD_NUMBER = 4;
    private waldo_protobuffs.UtilProto.UUID resourceUuid_;
    public boolean hasResourceUuid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public waldo_protobuffs.UtilProto.UUID getResourceUuid() {
      return resourceUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getResourceUuidOrBuilder() {
      return resourceUuid_;
    }
    
    private void initFields() {
      eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      removedSubscriberUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      hostUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      resourceUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasEventUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemovedSubscriberUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHostUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResourceUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEventUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRemovedSubscriberUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHostUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getResourceUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, eventUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, removedSubscriberUuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, hostUuid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, resourceUuid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, eventUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, removedSubscriberUuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, hostUuid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, resourceUuid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return waldo_protobuffs.PartnerRemovedSubscriberProto.internal_static_PartnerRemovedSubscriber_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return waldo_protobuffs.PartnerRemovedSubscriberProto.internal_static_PartnerRemovedSubscriber_fieldAccessorTable;
      }
      
      // Construct using waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventUuidFieldBuilder();
          getRemovedSubscriberUuidFieldBuilder();
          getHostUuidFieldBuilder();
          getResourceUuidFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (eventUuidBuilder_ == null) {
          eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (removedSubscriberUuidBuilder_ == null) {
          removedSubscriberUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          removedSubscriberUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (hostUuidBuilder_ == null) {
          hostUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          hostUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (resourceUuidBuilder_ == null) {
          resourceUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          resourceUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber.getDescriptor();
      }
      
      public waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber getDefaultInstanceForType() {
        return waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber.getDefaultInstance();
      }
      
      public waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber build() {
        waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber buildPartial() {
        waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber result = new waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (eventUuidBuilder_ == null) {
          result.eventUuid_ = eventUuid_;
        } else {
          result.eventUuid_ = eventUuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (removedSubscriberUuidBuilder_ == null) {
          result.removedSubscriberUuid_ = removedSubscriberUuid_;
        } else {
          result.removedSubscriberUuid_ = removedSubscriberUuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (hostUuidBuilder_ == null) {
          result.hostUuid_ = hostUuid_;
        } else {
          result.hostUuid_ = hostUuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (resourceUuidBuilder_ == null) {
          result.resourceUuid_ = resourceUuid_;
        } else {
          result.resourceUuid_ = resourceUuidBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber) {
          return mergeFrom((waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber other) {
        if (other == waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber.getDefaultInstance()) return this;
        if (other.hasEventUuid()) {
          mergeEventUuid(other.getEventUuid());
        }
        if (other.hasRemovedSubscriberUuid()) {
          mergeRemovedSubscriberUuid(other.getRemovedSubscriberUuid());
        }
        if (other.hasHostUuid()) {
          mergeHostUuid(other.getHostUuid());
        }
        if (other.hasResourceUuid()) {
          mergeResourceUuid(other.getResourceUuid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasEventUuid()) {
          
          return false;
        }
        if (!hasRemovedSubscriberUuid()) {
          
          return false;
        }
        if (!hasHostUuid()) {
          
          return false;
        }
        if (!hasResourceUuid()) {
          
          return false;
        }
        if (!getEventUuid().isInitialized()) {
          
          return false;
        }
        if (!getRemovedSubscriberUuid().isInitialized()) {
          
          return false;
        }
        if (!getHostUuid().isInitialized()) {
          
          return false;
        }
        if (!getResourceUuid().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasEventUuid()) {
                subBuilder.mergeFrom(getEventUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEventUuid(subBuilder.buildPartial());
              break;
            }
            case 18: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasRemovedSubscriberUuid()) {
                subBuilder.mergeFrom(getRemovedSubscriberUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRemovedSubscriberUuid(subBuilder.buildPartial());
              break;
            }
            case 26: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasHostUuid()) {
                subBuilder.mergeFrom(getHostUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHostUuid(subBuilder.buildPartial());
              break;
            }
            case 34: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasResourceUuid()) {
                subBuilder.mergeFrom(getResourceUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setResourceUuid(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .UUID event_uuid = 1;
      private waldo_protobuffs.UtilProto.UUID eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> eventUuidBuilder_;
      public boolean hasEventUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public waldo_protobuffs.UtilProto.UUID getEventUuid() {
        if (eventUuidBuilder_ == null) {
          return eventUuid_;
        } else {
          return eventUuidBuilder_.getMessage();
        }
      }
      public Builder setEventUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventUuid_ = value;
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setEventUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = builderForValue.build();
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeEventUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              eventUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            eventUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(eventUuid_).mergeFrom(value).buildPartial();
          } else {
            eventUuid_ = value;
          }
          onChanged();
        } else {
          eventUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearEventUuid() {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getEventUuidBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEventUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
        if (eventUuidBuilder_ != null) {
          return eventUuidBuilder_.getMessageOrBuilder();
        } else {
          return eventUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getEventUuidFieldBuilder() {
        if (eventUuidBuilder_ == null) {
          eventUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  eventUuid_,
                  getParentForChildren(),
                  isClean());
          eventUuid_ = null;
        }
        return eventUuidBuilder_;
      }
      
      // required .UUID removed_subscriber_uuid = 2;
      private waldo_protobuffs.UtilProto.UUID removedSubscriberUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> removedSubscriberUuidBuilder_;
      public boolean hasRemovedSubscriberUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public waldo_protobuffs.UtilProto.UUID getRemovedSubscriberUuid() {
        if (removedSubscriberUuidBuilder_ == null) {
          return removedSubscriberUuid_;
        } else {
          return removedSubscriberUuidBuilder_.getMessage();
        }
      }
      public Builder setRemovedSubscriberUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (removedSubscriberUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          removedSubscriberUuid_ = value;
          onChanged();
        } else {
          removedSubscriberUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setRemovedSubscriberUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (removedSubscriberUuidBuilder_ == null) {
          removedSubscriberUuid_ = builderForValue.build();
          onChanged();
        } else {
          removedSubscriberUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeRemovedSubscriberUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (removedSubscriberUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              removedSubscriberUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            removedSubscriberUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(removedSubscriberUuid_).mergeFrom(value).buildPartial();
          } else {
            removedSubscriberUuid_ = value;
          }
          onChanged();
        } else {
          removedSubscriberUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearRemovedSubscriberUuid() {
        if (removedSubscriberUuidBuilder_ == null) {
          removedSubscriberUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          removedSubscriberUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getRemovedSubscriberUuidBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRemovedSubscriberUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getRemovedSubscriberUuidOrBuilder() {
        if (removedSubscriberUuidBuilder_ != null) {
          return removedSubscriberUuidBuilder_.getMessageOrBuilder();
        } else {
          return removedSubscriberUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getRemovedSubscriberUuidFieldBuilder() {
        if (removedSubscriberUuidBuilder_ == null) {
          removedSubscriberUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  removedSubscriberUuid_,
                  getParentForChildren(),
                  isClean());
          removedSubscriberUuid_ = null;
        }
        return removedSubscriberUuidBuilder_;
      }
      
      // required .UUID host_uuid = 3;
      private waldo_protobuffs.UtilProto.UUID hostUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> hostUuidBuilder_;
      public boolean hasHostUuid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public waldo_protobuffs.UtilProto.UUID getHostUuid() {
        if (hostUuidBuilder_ == null) {
          return hostUuid_;
        } else {
          return hostUuidBuilder_.getMessage();
        }
      }
      public Builder setHostUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (hostUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hostUuid_ = value;
          onChanged();
        } else {
          hostUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setHostUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (hostUuidBuilder_ == null) {
          hostUuid_ = builderForValue.build();
          onChanged();
        } else {
          hostUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeHostUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (hostUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              hostUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            hostUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(hostUuid_).mergeFrom(value).buildPartial();
          } else {
            hostUuid_ = value;
          }
          onChanged();
        } else {
          hostUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearHostUuid() {
        if (hostUuidBuilder_ == null) {
          hostUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          hostUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getHostUuidBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getHostUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getHostUuidOrBuilder() {
        if (hostUuidBuilder_ != null) {
          return hostUuidBuilder_.getMessageOrBuilder();
        } else {
          return hostUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getHostUuidFieldBuilder() {
        if (hostUuidBuilder_ == null) {
          hostUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  hostUuid_,
                  getParentForChildren(),
                  isClean());
          hostUuid_ = null;
        }
        return hostUuidBuilder_;
      }
      
      // required .UUID resource_uuid = 4;
      private waldo_protobuffs.UtilProto.UUID resourceUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> resourceUuidBuilder_;
      public boolean hasResourceUuid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public waldo_protobuffs.UtilProto.UUID getResourceUuid() {
        if (resourceUuidBuilder_ == null) {
          return resourceUuid_;
        } else {
          return resourceUuidBuilder_.getMessage();
        }
      }
      public Builder setResourceUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (resourceUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resourceUuid_ = value;
          onChanged();
        } else {
          resourceUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setResourceUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (resourceUuidBuilder_ == null) {
          resourceUuid_ = builderForValue.build();
          onChanged();
        } else {
          resourceUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeResourceUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (resourceUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              resourceUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            resourceUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(resourceUuid_).mergeFrom(value).buildPartial();
          } else {
            resourceUuid_ = value;
          }
          onChanged();
        } else {
          resourceUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearResourceUuid() {
        if (resourceUuidBuilder_ == null) {
          resourceUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          resourceUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getResourceUuidBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getResourceUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getResourceUuidOrBuilder() {
        if (resourceUuidBuilder_ != null) {
          return resourceUuidBuilder_.getMessageOrBuilder();
        } else {
          return resourceUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getResourceUuidFieldBuilder() {
        if (resourceUuidBuilder_ == null) {
          resourceUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  resourceUuid_,
                  getParentForChildren(),
                  isClean());
          resourceUuid_ = null;
        }
        return resourceUuidBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:PartnerRemovedSubscriber)
    }
    
    static {
      defaultInstance = new PartnerRemovedSubscriber(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartnerRemovedSubscriber)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartnerRemovedSubscriber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartnerRemovedSubscriber_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036partnerRemovedSubscriber.proto\032\nutil.p" +
      "roto\"\225\001\n\030PartnerRemovedSubscriber\022\031\n\neve" +
      "nt_uuid\030\001 \002(\0132\005.UUID\022&\n\027removed_subscrib" +
      "er_uuid\030\002 \002(\0132\005.UUID\022\030\n\thost_uuid\030\003 \002(\0132" +
      "\005.UUID\022\034\n\rresource_uuid\030\004 \002(\0132\005.UUIDB1\n\020" +
      "waldo_protobuffsB\035PartnerRemovedSubscrib" +
      "erProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PartnerRemovedSubscriber_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PartnerRemovedSubscriber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartnerRemovedSubscriber_descriptor,
              new java.lang.String[] { "EventUuid", "RemovedSubscriberUuid", "HostUuid", "ResourceUuid", },
              waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber.class,
              waldo_protobuffs.PartnerRemovedSubscriberProto.PartnerRemovedSubscriber.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          waldo_protobuffs.UtilProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
