// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partnerNotifyOfPeeredModifiedResponse.proto

package waldo_protobuffs;

public final class PartnerNotifyOfPeeredModifiedResponseProto {
  private PartnerNotifyOfPeeredModifiedResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PartnerNotifyOfPeeredModifiedResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .UUID event_uuid = 1;
    boolean hasEventUuid();
    waldo_protobuffs.UtilProto.UUID getEventUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder();
    
    // required bool invalidated = 2;
    boolean hasInvalidated();
    boolean getInvalidated();
    
    // required .UUID reply_to_uuid = 3;
    boolean hasReplyToUuid();
    waldo_protobuffs.UtilProto.UUID getReplyToUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getReplyToUuidOrBuilder();
  }
  public static final class PartnerNotifyOfPeeredModifiedResponse extends
      com.google.protobuf.GeneratedMessage
      implements PartnerNotifyOfPeeredModifiedResponseOrBuilder {
    // Use PartnerNotifyOfPeeredModifiedResponse.newBuilder() to construct.
    private PartnerNotifyOfPeeredModifiedResponse(Builder builder) {
      super(builder);
    }
    private PartnerNotifyOfPeeredModifiedResponse(boolean noInit) {}
    
    private static final PartnerNotifyOfPeeredModifiedResponse defaultInstance;
    public static PartnerNotifyOfPeeredModifiedResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartnerNotifyOfPeeredModifiedResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.internal_static_PartnerNotifyOfPeeredModifiedResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.internal_static_PartnerNotifyOfPeeredModifiedResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .UUID event_uuid = 1;
    public static final int EVENT_UUID_FIELD_NUMBER = 1;
    private waldo_protobuffs.UtilProto.UUID eventUuid_;
    public boolean hasEventUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public waldo_protobuffs.UtilProto.UUID getEventUuid() {
      return eventUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
      return eventUuid_;
    }
    
    // required bool invalidated = 2;
    public static final int INVALIDATED_FIELD_NUMBER = 2;
    private boolean invalidated_;
    public boolean hasInvalidated() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getInvalidated() {
      return invalidated_;
    }
    
    // required .UUID reply_to_uuid = 3;
    public static final int REPLY_TO_UUID_FIELD_NUMBER = 3;
    private waldo_protobuffs.UtilProto.UUID replyToUuid_;
    public boolean hasReplyToUuid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public waldo_protobuffs.UtilProto.UUID getReplyToUuid() {
      return replyToUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getReplyToUuidOrBuilder() {
      return replyToUuid_;
    }
    
    private void initFields() {
      eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      invalidated_ = false;
      replyToUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasEventUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInvalidated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReplyToUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEventUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getReplyToUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, eventUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, invalidated_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, replyToUuid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, eventUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, invalidated_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, replyToUuid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.internal_static_PartnerNotifyOfPeeredModifiedResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.internal_static_PartnerNotifyOfPeeredModifiedResponse_fieldAccessorTable;
      }
      
      // Construct using waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventUuidFieldBuilder();
          getReplyToUuidFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (eventUuidBuilder_ == null) {
          eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        invalidated_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (replyToUuidBuilder_ == null) {
          replyToUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          replyToUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse.getDescriptor();
      }
      
      public waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse getDefaultInstanceForType() {
        return waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse.getDefaultInstance();
      }
      
      public waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse build() {
        waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse buildPartial() {
        waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse result = new waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (eventUuidBuilder_ == null) {
          result.eventUuid_ = eventUuid_;
        } else {
          result.eventUuid_ = eventUuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.invalidated_ = invalidated_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (replyToUuidBuilder_ == null) {
          result.replyToUuid_ = replyToUuid_;
        } else {
          result.replyToUuid_ = replyToUuidBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse) {
          return mergeFrom((waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse other) {
        if (other == waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse.getDefaultInstance()) return this;
        if (other.hasEventUuid()) {
          mergeEventUuid(other.getEventUuid());
        }
        if (other.hasInvalidated()) {
          setInvalidated(other.getInvalidated());
        }
        if (other.hasReplyToUuid()) {
          mergeReplyToUuid(other.getReplyToUuid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasEventUuid()) {
          
          return false;
        }
        if (!hasInvalidated()) {
          
          return false;
        }
        if (!hasReplyToUuid()) {
          
          return false;
        }
        if (!getEventUuid().isInitialized()) {
          
          return false;
        }
        if (!getReplyToUuid().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasEventUuid()) {
                subBuilder.mergeFrom(getEventUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEventUuid(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              invalidated_ = input.readBool();
              break;
            }
            case 26: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasReplyToUuid()) {
                subBuilder.mergeFrom(getReplyToUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReplyToUuid(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .UUID event_uuid = 1;
      private waldo_protobuffs.UtilProto.UUID eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> eventUuidBuilder_;
      public boolean hasEventUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public waldo_protobuffs.UtilProto.UUID getEventUuid() {
        if (eventUuidBuilder_ == null) {
          return eventUuid_;
        } else {
          return eventUuidBuilder_.getMessage();
        }
      }
      public Builder setEventUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventUuid_ = value;
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setEventUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = builderForValue.build();
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeEventUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              eventUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            eventUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(eventUuid_).mergeFrom(value).buildPartial();
          } else {
            eventUuid_ = value;
          }
          onChanged();
        } else {
          eventUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearEventUuid() {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getEventUuidBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEventUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
        if (eventUuidBuilder_ != null) {
          return eventUuidBuilder_.getMessageOrBuilder();
        } else {
          return eventUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getEventUuidFieldBuilder() {
        if (eventUuidBuilder_ == null) {
          eventUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  eventUuid_,
                  getParentForChildren(),
                  isClean());
          eventUuid_ = null;
        }
        return eventUuidBuilder_;
      }
      
      // required bool invalidated = 2;
      private boolean invalidated_ ;
      public boolean hasInvalidated() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getInvalidated() {
        return invalidated_;
      }
      public Builder setInvalidated(boolean value) {
        bitField0_ |= 0x00000002;
        invalidated_ = value;
        onChanged();
        return this;
      }
      public Builder clearInvalidated() {
        bitField0_ = (bitField0_ & ~0x00000002);
        invalidated_ = false;
        onChanged();
        return this;
      }
      
      // required .UUID reply_to_uuid = 3;
      private waldo_protobuffs.UtilProto.UUID replyToUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> replyToUuidBuilder_;
      public boolean hasReplyToUuid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public waldo_protobuffs.UtilProto.UUID getReplyToUuid() {
        if (replyToUuidBuilder_ == null) {
          return replyToUuid_;
        } else {
          return replyToUuidBuilder_.getMessage();
        }
      }
      public Builder setReplyToUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (replyToUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          replyToUuid_ = value;
          onChanged();
        } else {
          replyToUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setReplyToUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (replyToUuidBuilder_ == null) {
          replyToUuid_ = builderForValue.build();
          onChanged();
        } else {
          replyToUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeReplyToUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (replyToUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              replyToUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            replyToUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(replyToUuid_).mergeFrom(value).buildPartial();
          } else {
            replyToUuid_ = value;
          }
          onChanged();
        } else {
          replyToUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearReplyToUuid() {
        if (replyToUuidBuilder_ == null) {
          replyToUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          replyToUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getReplyToUuidBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getReplyToUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getReplyToUuidOrBuilder() {
        if (replyToUuidBuilder_ != null) {
          return replyToUuidBuilder_.getMessageOrBuilder();
        } else {
          return replyToUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getReplyToUuidFieldBuilder() {
        if (replyToUuidBuilder_ == null) {
          replyToUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  replyToUuid_,
                  getParentForChildren(),
                  isClean());
          replyToUuid_ = null;
        }
        return replyToUuidBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:PartnerNotifyOfPeeredModifiedResponse)
    }
    
    static {
      defaultInstance = new PartnerNotifyOfPeeredModifiedResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartnerNotifyOfPeeredModifiedResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartnerNotifyOfPeeredModifiedResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartnerNotifyOfPeeredModifiedResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+partnerNotifyOfPeeredModifiedResponse." +
      "proto\032\nutil.proto\"u\n%PartnerNotifyOfPeer" +
      "edModifiedResponse\022\031\n\nevent_uuid\030\001 \002(\0132\005" +
      ".UUID\022\023\n\013invalidated\030\002 \002(\010\022\034\n\rreply_to_u" +
      "uid\030\003 \002(\0132\005.UUIDB>\n\020waldo_protobuffsB*Pa" +
      "rtnerNotifyOfPeeredModifiedResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PartnerNotifyOfPeeredModifiedResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PartnerNotifyOfPeeredModifiedResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartnerNotifyOfPeeredModifiedResponse_descriptor,
              new java.lang.String[] { "EventUuid", "Invalidated", "ReplyToUuid", },
              waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse.class,
              waldo_protobuffs.PartnerNotifyOfPeeredModifiedResponseProto.PartnerNotifyOfPeeredModifiedResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          waldo_protobuffs.UtilProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
